#!/usr/bin/env python3
"""Rewrite the QQL data asset list in pubspec.yaml.

    python3 tool/gen-asset-list.py

Flutter does not recurse into asset directories — each one that holds files
has to be named. There are forty-odd of them under the QQL sources and they
change when a collection is added, so they are generated rather than kept by
hand. Run this after tool/fetch-qql.sh brings in a different release.

The generated block sits between the two markers below; everything else in
pubspec.yaml is left alone.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "third_party/qql/sources"

BEGIN = "    # BEGIN qql-data (generated by tool/gen-asset-list.py)\n"
END = "    # END qql-data\n"


def directories() -> list[str]:
    """Every directory under sources/ that directly holds a file."""
    found = {
        child.parent for child in SOURCES.rglob("*") if child.is_file()
    }
    # The bundle root too: it holds VERSION, which stamps the copy that
    # gets unpacked on Android. Flutter does not recurse, so this picks up
    # VERSION and LICENSE.md and not the 120 MB below them.
    return ["third_party/qql/"] + sorted(
        f"{d.relative_to(ROOT).as_posix()}/" for d in found
    )


def main() -> None:
    if not SOURCES.is_dir():
        raise SystemExit(f"No data at {SOURCES} — run tool/fetch-qql.sh first")

    dirs = directories()
    block = BEGIN + "".join(f"    - {d}\n" for d in dirs) + END

    pubspec = ROOT / "pubspec.yaml"
    text = pubspec.read_text()

    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        text = text[:start] + block + text[end:]
    else:
        # First run: put it directly after the existing asset entries.
        anchor = "    - assets/icon/\n"
        if anchor not in text:
            raise SystemExit("Could not find the assets section in pubspec.yaml")
        at = text.index(anchor) + len(anchor)
        text = text[:at] + block + text[at:]

    pubspec.write_text(text)

    files = sum(1 for f in SOURCES.rglob("*") if f.is_file())
    size = sum(f.stat().st_size for f in SOURCES.rglob("*") if f.is_file())
    print(f"{len(dirs)} directories, {files} files, {size / 1048576:.0f} MB")


if __name__ == "__main__":
    main()
